#!/bin/bash

echo "success"
#/usr/sbin/partclone.fat32 -c -s /dev/vda1 | gzip -c - > efi.img.gz
#/usr/sbin/partclone.ext4 -c -s /dev/vda2 | gzip -c - > boot.img.gz
#/usr/sbin/partclone.ext4 -c -s /dev/vda2 | gzip -c - > root.img.gz
/bin/bash
